---
abstract: 'encode and decode BIFCODE serialization format'
author:
  - 'Mark Lawrencde <nomad@null.net>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test2::V0: '0'
  Text::Diff: '0'
configure_requires:
  ExtUtils::MakeMaker::CPANfile: '0.08'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Bifcode
no_index:
  directory:
    - t
    - inc
  package:
    - Bifcode::BIFCODE
requires:
  Carp: '0'
  Exporter::Tidy: '0'
  boolean: '0'
  perl: '5.010'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  repository: ssh://git@github.com/mlawren/p5-Bifcode.git
version: 2.000_8
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
