---
abstract: 'simple serialization format (version 2)'
author:
  - 'Mark Lawrence <nomad@null.net>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test2::V0: '0'
configure_requires:
  ExtUtils::MakeMaker::CPANfile: '0.09'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.64, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Bifcode2
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Exporter::Tidy: '0'
  boolean: '0'
  perl: '5.010'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  repository: ssh://git@github.com/mlawren/p5-Bifcode.git
version: v2.0.0_13
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
